cat:
	echo hi tony
	cat Makefile

build:
	conda config --add channels conda-forge --force
	#(source activate base; conda install mamba -y ; mamba env create -f bunny37_env.yml python=3.8.0)
	(conda install mamba -y ; mamba env create -f bunny37_env.yml python=3.8.0)

