down:
	wget https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh
	mv Mini* /tmp

install:
	echo /data2/$USER
	mkdir /data2/tmpconda
	TMPDIR=/data2/tmpconda bash /tmp/Miniconda3-latest-Linux-x86_64.sh
